/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Character = IDL.Record({
  'name' : IDL.Text,
  'defense' : IDL.Nat,
  'cursedEnergy' : IDL.Nat,
  'attack' : IDL.Nat,
  'health' : IDL.Nat,
});
export const Match = IDL.Record({
  'score' : IDL.Nat,
  'currentTurn' : IDL.Nat,
  'player1' : Character,
  'player2' : Character,
});

export const idlService = IDL.Service({
  'createMatch' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
  'getCharactersByAttack' : IDL.Func([], [IDL.Vec(Character)], ['query']),
  'getCharactersByDefense' : IDL.Func([], [IDL.Vec(Character)], ['query']),
  'getCharactersByEnergy' : IDL.Func([], [IDL.Vec(Character)], ['query']),
  'getMatch' : IDL.Func([IDL.Nat], [Match], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Character = IDL.Record({
    'name' : IDL.Text,
    'defense' : IDL.Nat,
    'cursedEnergy' : IDL.Nat,
    'attack' : IDL.Nat,
    'health' : IDL.Nat,
  });
  const Match = IDL.Record({
    'score' : IDL.Nat,
    'currentTurn' : IDL.Nat,
    'player1' : Character,
    'player2' : Character,
  });
  
  return IDL.Service({
    'createMatch' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
    'getCharactersByAttack' : IDL.Func([], [IDL.Vec(Character)], ['query']),
    'getCharactersByDefense' : IDL.Func([], [IDL.Vec(Character)], ['query']),
    'getCharactersByEnergy' : IDL.Func([], [IDL.Vec(Character)], ['query']),
    'getMatch' : IDL.Func([IDL.Nat], [Match], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };