/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DomainExpansion = IDL.Record({
  'name' : IDL.Text,
  'defenseBoost' : IDL.Nat,
  'effect' : IDL.Text,
  'powerBoost' : IDL.Nat,
  'damageReduction' : IDL.Nat,
});
export const Character = IDL.Record({
  'elementalResistances' : IDL.Record({
    'fire' : IDL.Nat,
    'wind' : IDL.Nat,
    'lightning' : IDL.Nat,
  }),
  'name' : IDL.Text,
  'moveset' : IDL.Vec(IDL.Text),
  'virusType' : IDL.Opt(IDL.Text),
  'speed' : IDL.Nat,
  'defense' : IDL.Nat,
  'cursedEnergy' : IDL.Nat,
  'ultimate' : IDL.Text,
  'personalBest' : IDL.Nat,
  'abilities' : IDL.Vec(IDL.Text),
  'attack' : IDL.Nat,
  'domainExpansion' : DomainExpansion,
  'health' : IDL.Nat,
  'elementalAffinity' : IDL.Text,
});
export const Battle = IDL.Record({
  'score' : IDL.Nat,
  'currentTurn' : IDL.Nat,
  'player1' : Character,
  'player2' : Character,
});

export const idlService = IDL.Service({
  'createBattle' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
  'executeDomainExpansion' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Text], []),
  'getAllCharacters' : IDL.Func([], [IDL.Vec(Character)], ['query']),
  'getBattle' : IDL.Func([IDL.Nat], [Battle], ['query']),
  'getCharacterByName' : IDL.Func([IDL.Text], [Character], ['query']),
  'getCharactersByAttack' : IDL.Func([], [IDL.Vec(Character)], ['query']),
  'getCharactersByDefense' : IDL.Func([], [IDL.Vec(Character)], ['query']),
  'getCharactersByEnergy' : IDL.Func([], [IDL.Vec(Character)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DomainExpansion = IDL.Record({
    'name' : IDL.Text,
    'defenseBoost' : IDL.Nat,
    'effect' : IDL.Text,
    'powerBoost' : IDL.Nat,
    'damageReduction' : IDL.Nat,
  });
  const Character = IDL.Record({
    'elementalResistances' : IDL.Record({
      'fire' : IDL.Nat,
      'wind' : IDL.Nat,
      'lightning' : IDL.Nat,
    }),
    'name' : IDL.Text,
    'moveset' : IDL.Vec(IDL.Text),
    'virusType' : IDL.Opt(IDL.Text),
    'speed' : IDL.Nat,
    'defense' : IDL.Nat,
    'cursedEnergy' : IDL.Nat,
    'ultimate' : IDL.Text,
    'personalBest' : IDL.Nat,
    'abilities' : IDL.Vec(IDL.Text),
    'attack' : IDL.Nat,
    'domainExpansion' : DomainExpansion,
    'health' : IDL.Nat,
    'elementalAffinity' : IDL.Text,
  });
  const Battle = IDL.Record({
    'score' : IDL.Nat,
    'currentTurn' : IDL.Nat,
    'player1' : Character,
    'player2' : Character,
  });
  
  return IDL.Service({
    'createBattle' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
    'executeDomainExpansion' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Text], []),
    'getAllCharacters' : IDL.Func([], [IDL.Vec(Character)], ['query']),
    'getBattle' : IDL.Func([IDL.Nat], [Battle], ['query']),
    'getCharacterByName' : IDL.Func([IDL.Text], [Character], ['query']),
    'getCharactersByAttack' : IDL.Func([], [IDL.Vec(Character)], ['query']),
    'getCharactersByDefense' : IDL.Func([], [IDL.Vec(Character)], ['query']),
    'getCharactersByEnergy' : IDL.Func([], [IDL.Vec(Character)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };